DEFAULT_REFRESH_DELAY: int = 1
DEFAULT_REFRESH_TIMEOUT: int = 30
DEFAULT_ACQUIRE_TIMEOUT: float = 1.0
DEFAULT_MASTER_AS_REPLICA_WEIGHT: float = 0.0
DEFAULT_STOPWATCH_WINDOW_SIZE: int = 128

__all__ = (
    "DEFAULT_REFRESH_DELAY",
    "DEFAULT_REFRESH_TIMEOUT",
    "DEFAULT_ACQUIRE_TIMEOUT",
    "DEFAULT_MASTER_AS_REPLICA_WEIGHT",
    "DEFAULT_STOPWATCH_WINDOW_SIZE",
)
