name: tox

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        linter:
          - lint
          - mypy

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install tox 4.49.0
        run: python3 -m pip install "tox==4.49.0"
      - name: Run tox ${{ matrix.linter }}
        run: tox
        env:
          TOXENV: ${{ matrix.linter }}

  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test

    strategy:
      fail-fast: false

      matrix:
        include:
          - toxenv: py310
            python-version: "3.10"
          - toxenv: py311
            python-version: "3.11"
          - toxenv: py312
            python-version: "3.12"
          - toxenv: py313
            python-version: "3.13"
          - toxenv: py314
            python-version: "3.14"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox 4.49.0
        run: python3 -m pip install "tox==4.49.0"
      - name: Run tox ${{ matrix.toxenv }}
        run: tox
        env:
          FORCE_COLOR: 1
          TOXENV: ${{ matrix.toxenv }}
          PG_DSN: postgres://test:test@localhost:5432/test
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
